name: Flutter CI - Debug windows build

on: [push, pull_request]

jobs:
  build:
    # Runs on Windows Server 2019
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.5.x'
    
    - name: Disable Google Analytics
      run: flutter config --no-analytics
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Enable desktop support
      run: flutter config --enable-windows-desktop
    
    - name: Build debug windows version
      run: flutter build windows --debug
    
    - name: Uploading debug build for windows (64-bit)
      uses: actions/upload-artifact@v2
      with:
        name: MP-debug-windows-x86_64-commit-${{github.sha}}
        path: build\windows\runner\Debug\