name: name: Flutter CI - Debug windows build

on: [push, pull_request]

jobs:
  build:
    # Runs on Windows Server 2019
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.5.x'
    - name: Disable Google Analytics
      run: flutter config --no-analytics
    - name: Install dependencies
      run: flutter pub get
    - name: Enable desktop support
      run: flutter config --enable-windows-desktop
    - name: Build debug windows version
      run: flutter build windows --debug
    # This step commented because linux-related part is not included into project yet
    # - name: Enable desktop support
    #   run: flutter config --enable-linux-desktop
    # - name: Install Linux dependencies
    #   run: sudo apt update && sudo apt install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libjsoncpp1 libsecret-1-dev libsecret-1-0 librhash0 libsqlite3-dev libappindicator3-dev gettext -y
    # - name: Build debug Linux binary
    #   run: flutter build linux --debug
